export const iconPath = '/icons'
export const iconType = [
  'account--default',
  'account--primary',
  'account--multiple',
  'alert--error',
  'alert-outline--error',
  'alert--white',
  'calendar--default',
  'cart--default',
  'chart-bar--white',
  'check--white',
  'chevron-down--default',
  'chevron-down--white',
  'chevron-right--default',
  'chevron-right--error',
  'chevron-right--link',
  'chevron-right--success',
  'chevron-right--white',
  'circle-check--primary',
  'circle-check--success',
  'circle-close--default',
  'circle-play--white',
  'circle-waiting--warning',
  'creative--default',
  'creative--white',
  'download--default',
  'file--primary',
  'filter--primary',
  'folder--primary',
  'history--white',
  'house--white',
  'triangle--default',
  'tv--default',
  'information--accent',
  'information--primary',
  'information--alert',
  'notification--default',
  'planning--white',
  'question--default',
  'question--primary',
  'speaker--primary',
  'upload--default',
  'v-dots--default',
  'plus--default',
  'qr--primary',
] as const
export type IconType = typeof iconType[number]
