name: Deploy to Firebase Hosting on PR
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: |
          yarn
          yarn add firebase-tools
      - name: lint and test
        run: |
          yarn run lint
          yarn run test
      - run: yarn build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMO_3C2C7 }}'
          projectId: memo-3c2c7
          channelId: live
