name: Deploy to Firebase Hosting on PR
'on':
  push:
    branches:
      - develop
  pull_request:
    branches:
      - 'main'
      - 'develop'
jobs:
  test:
    name: Execute React Test
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: |
          yarn
          yarn add firebase-tools
      - name: lint and test
        run: |
          yarn run lint
          yarn run test
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install
        run: |
          yarn
          yarn add firebase-tools
      - run: yarn build:dev
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMO_DEVELOP }}'
          channelId: live
          projectId: memo-develop
